### ISSUE TITLE
[Documentation] Task list not rendered in README.md

### ISSUE THREAD

**Issue by alexlemaire** [kaskadi/template-kaskadi-element#1]
**WIP, just filing the issue here to keep track**

Interactive task list not being rendered correctly in README.md.

Tried:
- regular Markdown syntax: `- [ ] task`
- HTML: `<li><input type="checkbox"> task</li>`

**Comment by alexlemaire** [comment]
_For reference_:
- the regular Markdown syntax does not work because it's rendering a static task list that you can only modify via Markdown itself. The reason it works differently in Pull requests, Comments or Issues is because those uses [GitHub Flavored Markdown](https://github.github.com/gfm/) syntax instead which allows extra features. Unfortunately it's not available for regular READMEs
- the HTML syntax does not work because GitHub Markdown rendering is blacklisting `input` HTML element as well as inline styles (see [here](https://stackoverflow.com/questions/44831505/which-inline-html-styles-does-github-markdown-accept) and [here](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/sanitization_filter.rb#L45-L49)). Therefore the only thing that goes through is the `ul`, the `li`'s and their content

**Comment by Holger-Will** [comment]
this is not needed, see new readme... we just have a list and delete each task from that list when it's done. the list must be deleted anyways when the element is done ;-)

**Comment by alexlemaire** [comment]
All good, closing for now.
