### ISSUE TITLE
Separated scripts for coverage and test?

### ISSUE THREAD

**Issue by alexlemaire** [kaskadi/template-kaskadi-element#13]
Why do we currently have 2 different scripts for `coverage` and `test`?

```
"scripts": {
    "example": "xdg-open localhost:1234/example && serve -l 1234",
    "test": "npm run lint && npm run test.All",
    ...
    "coverage": "npm run lint && npm run test.Chrome"
  },
```

Shouldn't we use `coverage` or `test` only and both should run `test.All` (instead of `coverage` running only `test.Chrome`)?

**Comment by Holger-Will** [comment]
for coverage testing, one browser is enough because one test already creates all coverage information.
finding error in one of the browsers needs testing in all of them... that why I split it. 

saves a few cycles on github actions :-)

**Comment by alexlemaire** [comment]
Alright I see now :+1: 

Closing this then!
