### ISSUE TITLE
[Badges] Code Climate badges API potential issue

### ISSUE THREAD

**Issue by alexlemaire** [kaskadi/template-kaskadi-element#14]
Sometimes _CodeClimate_ badges are displaying `invalid`.

I found something that could be related [here](https://github.com/badges/shields/issues/1518)

Let's see if it persists since I saw it for the first time today.

**Comment by Holger-Will** [comment]
never saw it here... might really be a rate limit issue

**Comment by alexlemaire** [comment]
Could be yep. I'll close for now then :)

**Comment by PyvesB** [comment]
@alexlemaire out of interest, have you seen any of these issues recently?

**Comment by alexlemaire** [comment]
@PyvesB no I didn't see it in a while. That being said I'm also opening the previews for my README's/checking the main page of my repos less frequently than I was back then (when we started building this template). So that may be the reason!
