### ISSUE TITLE
JSDoc integration?

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/template-kaskadi-element#16]
should we integrate with JSDoc?

**Comment by alexlemaire** [comment]
We can give it a shot yep

**Comment by alexlemaire** [comment]
There is now a new action [`action-generate-docs`](https://github.com/kaskadi/action-generate-docs) that can be used in a workflow to automatically generate documentation for a repository.

As for now it supports `action` and `package` type of repository. The documentation is built using the following logic:
- `action` uses `action.yml` metadata file from the action
- `package` uses `JSDoc` comments style
- for any type of repository we can pass a template (`.md` file containing a `{{>main}}` token) which will be used as base for the documentation and in which `{{>main}}` will be replace by the actual output from the documentation generator
- all documentation is written in `README.md`

All actions (template included) as well as all currently published NPM packages (template included) now uses this action to generate their documentation. CI/CD pipeline integration as follow:
- `action`: a separate `generate-docs` workflow generates the documentation automatically and pushes it
- `package`: a `generate-docs` job inside of `publish` workflow generates and pushes the documentation. `publish` job inside of `publish` workflow waits on `generate-docs` to finish and then will pull any new documentation before publishing the package

All documentations are pushed by our `kaskadi-bot` (GPG signed) but that can be modified.

**Support for `layer`, `lambda`, `element`, `api` incoming**

Closing for now!
