### ISSUE TITLE
Dependencies update watcher

### ISSUE THREAD

**Issue by alexlemaire** [kaskadi/template-kaskadi-element#18]
@Holger-Will I found [this tool](https://david-dm.org/) for watching our repo dependencies and displaying info on whether they are up to date or outdated.

Do we want to use this?

**Comment by Holger-Will** [comment]
please use https://greenkeeper.io/ for that

**Comment by alexlemaire** [comment]
Closing since there is a [dedicated issue](https://github.com/kaskadi/template-action/issues/2) for it now
