### ISSUE TITLE
set up code coverage and reporter

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/template-kaskadi-element#2]
<s>use karmas Istanbul integration</s> and report to [code-climate](https://docs.codeclimate.com/docs/github-actions-test-coverage)

**Comment by Holger-Will** [comment]
part one (istanbul) is done

**Comment by Holger-Will** [comment]
you can now run coverage upload manually: `npm run coverage`
we need to automate this with actions... the process requires a manuell set up of the repo at code-climate

**Comment by Holger-Will** [comment]
https://docs.codeclimate.com/docs/github-actions-test-coverage

**Comment by alexlemaire** [comment]
Action for code testing and code coverage in place. Needs to document the initial repo setup so that the automation can run

**Comment by Holger-Will** [comment]
can this be closed?

**Comment by alexlemaire** [comment]
Yep, closing.
