### ISSUE TITLE
[LGTM] Setup automatic report on push

### ISSUE THREAD

**Issue by alexlemaire** [kaskadi/template-kaskadi-element#9]
LGTM is generating a report the first time we follow a repo.
It also does automatic reporting on pull requests but not on push.

So in order to get an updated report for each push, we can implement automated LGTM API calls following this [doc](https://lgtm.com/help/lgtm/api/run-code-review)

**Comment by Holger-Will** [comment]
it does update the reports every 24 hours. I think that should be enough...

**Comment by Holger-Will** [comment]
we should not automate this, but we could add this feature to `kaskadi-cli` so you can force check a patch if you feel the need to... closing here and moving this to kaskadi-cli
